import type { Lead, Buyer } from "./types"

export const mockAvailableLeads: Lead[] = [
  {
    id: "1",
    title: "Healthcare Decision Makers - Fortune 500",
    category: "Healthcare",
    quality: "hot",
    price: 450,
    quantity: 100,
    seller: "MedLeads Elite",
    date: "2025-01-20",
    status: "available",
    description:
      "Verified decision makers from Fortune 500 healthcare companies with direct contact information and engagement history.",
  },
  {
    id: "2",
    title: "E-commerce Startup Founders",
    category: "E-commerce",
    quality: "warm",
    price: 275,
    quantity: 65,
    seller: "StartupConnect",
    date: "2025-01-19",
    status: "available",
    description: "Active e-commerce startup founders looking for B2B solutions and partnerships.",
  },
  {
    id: "3",
    title: "Financial Services Qualified Leads",
    category: "Finance",
    quality: "hot",
    price: 380,
    quantity: 80,
    seller: "FinancePro Leads",
    date: "2025-01-18",
    status: "available",
    description: "Pre-qualified leads from financial services sector actively seeking investment products.",
  },
  {
    id: "4",
    title: "Manufacturing SMB Contacts",
    category: "Manufacturing",
    quality: "cold",
    price: 150,
    quantity: 120,
    seller: "IndustryLeads",
    date: "2025-01-17",
    status: "available",
    description: "Small to medium manufacturing businesses with verified contact details.",
  },
  {
    id: "5",
    title: "Tech Startups Series A+",
    category: "Technology",
    quality: "hot",
    price: 520,
    quantity: 45,
    seller: "VentureLeads",
    date: "2025-01-16",
    status: "available",
    description: "High-value tech startups that have raised Series A or beyond, actively growing.",
  },
  {
    id: "6",
    title: "Retail Chain Decision Makers",
    category: "Retail",
    quality: "warm",
    price: 290,
    quantity: 70,
    seller: "RetailConnect Pro",
    date: "2025-01-15",
    status: "available",
    description: "Key decision makers from retail chains with 10+ locations nationwide.",
  },
]

export const mockPurchasedLeads: Lead[] = [
  {
    id: "p1",
    title: "Enterprise SaaS Leads - Q1 2025",
    category: "SaaS",
    quality: "hot",
    price: 299,
    quantity: 50,
    seller: "TechLeads Pro",
    date: "2025-01-15",
    status: "purchased",
    description: "Enterprise-level SaaS decision makers actively evaluating new solutions.",
  },
  {
    id: "p2",
    title: "Real Estate Qualified Buyers",
    category: "Real Estate",
    quality: "warm",
    price: 189,
    quantity: 30,
    seller: "PropertyConnect",
    date: "2025-01-12",
    status: "purchased",
    description: "Pre-qualified real estate buyers in high-value markets.",
  },
  {
    id: "p3",
    title: "B2B Marketing Qualified Leads",
    category: "Marketing",
    quality: "hot",
    price: 349,
    quantity: 75,
    seller: "LeadGen Masters",
    date: "2025-01-10",
    status: "purchased",
    description: "Marketing decision makers seeking B2B solutions and services.",
  },
  {
    id: "p4",
    title: "Tech Industry C-Level Executives",
    category: "Technology",
    quality: "hot",
    price: 499,
    quantity: 40,
    seller: "ExecutiveLeads",
    date: "2025-01-08",
    status: "purchased",
    description: "C-suite executives from tech companies with verified direct contact info.",
  },
  {
    id: "p5",
    title: "Healthcare Facility Managers",
    category: "Healthcare",
    quality: "warm",
    price: 225,
    quantity: 55,
    seller: "HealthConnect",
    date: "2025-01-05",
    status: "purchased",
    description: "Facility managers from hospitals and healthcare organizations.",
  },
]

export const mockSellerLeads: Lead[] = [
  {
    id: "s1",
    title: "Enterprise SaaS Leads - Q1 2025",
    category: "SaaS",
    quality: "hot",
    price: 299,
    quantity: 50,
    date: "2025-01-15",
    status: "available",
    description: "Enterprise-level SaaS decision makers actively evaluating new solutions.",
  },
  {
    id: "s2",
    title: "Real Estate Qualified Buyers",
    category: "Real Estate",
    quality: "warm",
    price: 189,
    quantity: 30,
    date: "2025-01-12",
    status: "purchased",
    description: "Pre-qualified real estate buyers in high-value markets.",
  },
  {
    id: "s3",
    title: "B2B Marketing Qualified Leads",
    category: "Marketing",
    quality: "hot",
    price: 349,
    quantity: 75,
    date: "2025-01-10",
    status: "available",
    description: "Marketing decision makers seeking B2B solutions and services.",
  },
  {
    id: "s4",
    title: "Tech Industry C-Level Executives",
    category: "Technology",
    quality: "hot",
    price: 499,
    quantity: 40,
    date: "2025-01-08",
    status: "purchased",
    description: "C-suite executives from tech companies with verified direct contact info.",
  },
  {
    id: "s5",
    title: "Healthcare Facility Managers",
    category: "Healthcare",
    quality: "warm",
    price: 225,
    quantity: 55,
    date: "2025-01-05",
    status: "available",
    description: "Facility managers from hospitals and healthcare organizations.",
  },
  {
    id: "s6",
    title: "E-commerce Store Owners",
    category: "E-commerce",
    quality: "cold",
    price: 145,
    quantity: 90,
    date: "2025-01-03",
    status: "pending",
    description: "Small to medium e-commerce store owners looking for growth solutions.",
  },
]

export const mockBuyers: Buyer[] = [
  {
    id: "1",
    name: "John Smith",
    company: "Acme Corp",
    totalPurchases: 12,
    totalSpent: 3650,
    lastPurchase: "2025-01-18",
    status: "active",
  },
  {
    id: "2",
    name: "Sarah Johnson",
    company: "TechStart Inc",
    totalPurchases: 8,
    totalSpent: 2240,
    lastPurchase: "2025-01-15",
    status: "active",
  },
  {
    id: "3",
    name: "Michael Chen",
    company: "Global Solutions",
    totalPurchases: 15,
    totalSpent: 4875,
    lastPurchase: "2025-01-12",
    status: "active",
  },
  {
    id: "4",
    name: "Emily Davis",
    company: "Marketing Pro",
    totalPurchases: 5,
    totalSpent: 1450,
    lastPurchase: "2024-12-28",
    status: "inactive",
  },
  {
    id: "5",
    name: "Robert Wilson",
    company: "Enterprise Ltd",
    totalPurchases: 20,
    totalSpent: 6200,
    lastPurchase: "2025-01-20",
    status: "active",
  },
]
